### ISSUE TITLE
Could not load type 'System.Web.Mvc.HttpAntiForgeryException' from assembly 'System.Web.WebPages, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#1019]
Downloaded the latest source code and when the application should start the
installer I get the following error:  
Could not load type 'System.Web.Mvc.HttpAntiForgeryException' from assembly
'System.Web.WebPages, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35'.  
  
Stack trace:  
  
  
[TypeLoadException: Could not load type
'System.Web.Mvc.HttpAntiForgeryException' from assembly 'System.Web.WebPages,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.]  
Orchard.Mvc.Html.HtmlHelperExtensions.AntiForgeryTokenOrchard(HtmlHelper
htmlHelper) +0  
Orchard.Mvc.Html.MvcFormAntiForgeryPost.Dispose(Boolean disposing) +120  
System.Web.Mvc.Html.MvcForm.Dispose() +20  
ASP.Index_cshtml.Execute() +5538  
System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +172  
System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +81  
System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext
pageContext, TextWriter writer, WebPageRenderingBase startPage) +86  
System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter
writer, Object instance) +220  
System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext,
TextWriter writer) +115  
Orchard.Mvc.ViewEngines.ThemeAwareness.<>c__DisplayClass7.<FindView>b__5(ViewC
ontext viewContext, TextWriter writer, IViewDataContainer viewDataContainer)
+214  
Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutView.Render(ViewContext
viewContext, TextWriter writer) +100  
System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +303  
System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext
controllerContext, ActionResult actionResult) +13  
System.Web.Mvc.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19() +23  
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter
filter, ResultExecutingContext preContext, Func ` 1 continuation) +260  
System.Web.Mvc.<>c__DisplayClass1e.<InvokeActionResultWithFilters>b__1b() +19  
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter
filter, ResultExecutingContext preContext, Func  ` 1 continuation) +260  
System.Web.Mvc.<>c__DisplayClass1e.<InvokeActionResultWithFilters>b__1b() +19  
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter
filter, ResultExecutingContext preContext, Func ` 1 continuation) +260  
System.Web.Mvc.<>c__DisplayClass1e.<InvokeActionResultWithFilters>b__1b() +19  
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter
filter, ResultExecutingContext preContext, Func  ` 1 continuation) +260  
System.Web.Mvc.<>c__DisplayClass1e.<InvokeActionResultWithFilters>b__1b() +19  
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter
filter, ResultExecutingContext preContext, Func ` 1 continuation) +260  
System.Web.Mvc.<>c__DisplayClass1e.<InvokeActionResultWithFilters>b__1b() +19  
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(Controlle
rContext controllerContext, IList  ` 1 filters, ActionResult actionResult)
+177  
System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext
controllerContext, String actionName) +343  
System.Web.Mvc.Controller.ExecuteCore() +116  
System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext) +97  
System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContex
t requestContext) +10  
System.Web.Mvc.<>c__DisplayClassb.<BeginProcessRequest>b__5() +37  
System.Web.Mvc.Async.<>c__DisplayClass1.<MakeVoidDelegate>b__0() +21  
System.Web.Mvc.Async.<>c__DisplayClass8 `
1.<BeginSynchronous>b__7(IAsyncResult _) +12  
System.Web.Mvc.Async.WrappedAsyncResult  ` 1.End() +62  
System.Web.Mvc.<>c__DisplayClasse.<EndProcessRequest>b__d() +50  
System.Web.Mvc.SecurityUtil.<GetCallInAppTrustThunk>b__0(Action f) +7  
System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Action action) +22  
System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +60  
System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyn
cResult result) +9  
Orchard.Mvc.Routes.HttpAsyncHandler.EndProcessRequest(IAsyncResult result) +55  
System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.
Execute() +8841105  
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&
completedSynchronously) +184  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 17129](http://orchard.codeplex.com/workitem/17129)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 17, 2010 at 1:35 PM
**Reported by:**	jkr
**Updated on:**	Dec 20, 2010 at 10:25 PM
**Updated by:**	BertrandLeRoy
**Closed on:**	Dec 20, 2010 at 10:25 PM
**Closed by:**	BertrandLeRoy
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 17, 2010 at 1:35 PM
**Reported by:**	jkr
**Updated on:**	Dec 20, 2010 at 10:25 PM
**Updated by:**	BertrandLeRoy
**Closed on:**	Dec 20, 2010 at 10:25 PM
**Closed by:**	BertrandLeRoy

**Comment by bleroy** [comment]
On *2010-12-18 09:19:01 UTC*, **rdaddis** commented:


I downloaded Orchard.Source.0.9.253.zip, rebuilt the solution, & hit <F5>:
System.TypeLoadException was unhandled by user code
Message=Could not load type 'System.Web.Mvc.HttpAntiForgeryException' from assembly 'System.Web.WebPages, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Source=Orchard.Framework
TypeName=System.Web.Mvc.HttpAntiForgeryException
StackTrace:
   at Orchard.Mvc.Html.HtmlHelperExtensions.AntiForgeryTokenOrchard(HtmlHelper htmlHelper)
   at Orchard.Mvc.Html.MvcFormAntiForgeryPost.Dispose(Boolean disposing)
   at System.Web.Mvc.Html.MvcForm.Dispose()
   at ASP.Index_cshtml.Execute()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.<>c__DisplayClass7.<FindView>b__5(ViewContext viewContext, TextWriter writer, IViewDataContainer viewDataContainer)
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.LayoutView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
InnerException:

**Comment by bleroy** [comment]
On *2010-12-18 10:25:24 UTC*, **rdaddis** commented:

Problem solved - I updated ASP.NET MVC from RC to RC2 & the setup ran smoothly!

**Comment by bleroy** [comment]
On *2010-12-18 10:28:04 UTC*, **rdaddis** commented:

eerrrr.... make that ASP.NET MVC 3 RC2 
:-)

**Comment by bleroy** [comment]
On *2010-12-18 12:08:31 UTC*, **JasonMueller** commented:

I had the same problem but already had MVC 3 RC2 installed. I ended up uninstalling MVC 3 RC2 (and ASP.NET Web Pages) and their associated Visual Studio Tools packages and reinstalling MVC 3 RC2 from Web Platform Installer which resolved the issue.

**Comment by bleroy** [comment]
On *2010-12-19 03:50:59 UTC*, **rpaquay** commented:

This is explained in the release notes of 0.9. Orchard will work in only 2 configurations: either no version of mvc 3/asp.net web pages is installed, or mvc 3 rc2 is installed. The reason for this is that each mvc 3 installation installs a different set
 of assemblies in the GAC, all with the same version number (3.0.0.0). This means that even though Orchard comes with the right set of assemblies in bin, they will be ignored at run time, as the assemblies installed in the GAC have precedence. This will be
 less of an issue for the final 1.0 release, as presumably, everybody will upgrade to mvc 3 rtm...
