### ISSUE TITLE
Images & smileys from Livewriter break blog publishing

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#1400]
Get a service error.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 17508](http://orchard.codeplex.com/workitem/17508)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 18, 2011 at 6:20 PM
**Reported by:**	jkresner
**Updated on:**	Apr 1, 2011 at 3:19 AM
**Updated by:**	JilkaBian
**Closed on:**	Apr 1, 2011 at 3:19 AM
**Closed by:**	JilkaBian
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 18, 2011 at 6:20 PM
**Reported by:**	jkresner
**Updated on:**	Apr 1, 2011 at 3:19 AM
**Updated by:**	JilkaBian
**Closed on:**	Apr 1, 2011 at 3:19 AM
**Closed by:**	JilkaBian

**Comment by bleroy** [comment]
On *2011-03-19 04:11:44 UTC*, **@BertrandLeRoy** commented:

I can't repro that but if we had a network trace of the actual error, once you've configured the site to give custom errors, that would really help figuring out what's happening here.

**Comment by bleroy** [comment]
On *2011-04-01 01:27:51 UTC*, **@BertrandLeRoy** commented:

Stack trace:

System.IO.DirectoryNotFoundException occurred
Message=Could not find a part of the path 'C:\Projects\Orchard\src\Orchard.Web\Media\Default\Windows-Live-Writer\Yeah_A0BF\HorribleBertrandHigh_2.png'.
Source=mscorlib
StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at Orchard.FileSystems.Media.FileSystemStorageProvider.CreateFile(String path)
InnerException:

**Comment by bleroy** [comment]
On *2011-04-01 09:44:30 UTC*, **@Yinhaixia** commented:

Not repro now in the latest bit. the post with image publish well in live writer
