### ISSUE TITLE
Theme list command fails

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#1454]
I have this command:  
  
theme list [/Summary:true|false]  

    
    
        Display list of available themes
    

But when I run it, I get this:  
  
  
Stack Trace:  
  
[NullReferenceException: Object reference not set to an instance of an
object.]  
at Orchard.Themes.Commands.ThemeCommands.<List>b__3(ExtensionDescriptor d)  
at System.Linq.Enumerable.WhereSelectEnumerableIterator ` 2.MoveNext()  
at System.Linq.Buffer  ` 1..ctor(IEnumerable ` 1 source)  
at System.Linq.Enumerable.ToArray[TSource](IEnumerable  ` 1 source)  
at Orchard.Themes.Commands.ThemeCommands.List()  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 17562](http://orchard.codeplex.com/workitem/17562)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	suhacan
**Reported on:**	Mar 26, 2011 at 8:10 AM
**Reported by:**	bradmi
**Updated on:**	Apr 2, 2011 at 8:57 AM
**Updated by:**	Yinhaixia
**Closed on:**	Mar 28, 2011 at 7:09 PM
**Closed by:**	suhacan
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	suhacan
**Reported on:**	Mar 26, 2011 at 8:10 AM
**Reported by:**	bradmi
**Updated on:**	Apr 2, 2011 at 8:57 AM
**Updated by:**	Yinhaixia
**Closed on:**	Mar 28, 2011 at 7:09 PM
**Closed by:**	suhacan

**Comment by bleroy** [comment]
On *2011-03-29 02:09:36 UTC*, **@suhacan** commented:

Seems to be working now.

**Comment by bleroy** [comment]
On *2011-04-02 15:57:48 UTC*, **@Yinhaixia** commented:

I'm afraid the bug repro again with the error:
Error executing command "theme list"
Object reference not set to an instance of an object.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
Stack Trace:
[NullReferenceException: Object reference not set to an instance of an object.]
at Orchard.Themes.Commands.ThemeCommands.<List>b__3(ExtensionDescriptor d)
at System.Linq.Enumerable.<>c__DisplayClassf1.<CombinePredicates>b__e(TSource x)
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at Orchard.Themes.Commands.ThemeCommands.List()
