### ISSUE TITLE
System.Security.Permissions.SecurityPermission

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#1711]
Hello,  
  
Environment  

  * default 1.1 source code from codeplex 
  * visual studio 2010 
  * Advanced Menu 1.2.1   

I run the website using Visual Studio Web Developement Server.  
I've installed the advanced menu 1.2.1 from the gallery. (later on i've also
included it into my solution)  
After i install it, and go to the homepage, when i click on the "HOME" button
which by default redirects me to the root of my application i get the
following error.  
  
System.Security.SecurityException was unhandled  
Message=Request for the permission of type
'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.  
Source=mscorlib  
GrantedSet=<PermissionSet class="System.Security.NamedPermissionSet"  
version="1"  
Name="ASP.Net">  
<IPermission class="System.Security.Permissions.EnvironmentPermission,
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Read="TEMP;TMP;USERNAME;OS;COMPUTERNAME"/>  
<IPermission class="System.Security.Permissions.FileIOPermission, mscorlib,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Read="D:\Orchard.Codeplex\src\Orchard.Web"  
Write="D:\Orchard.Codeplex\src\Orchard.Web"  
Append="D:\Orchard.Codeplex\src\Orchard.Web"  
PathDiscovery="D:\Orchard.Codeplex\src\Orchard.Web"/>  
<IPermission class="System.Security.Permissions.IsolatedStorageFilePermission,
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Allowed="AssemblyIsolationByUser"  
UserQuota="9223372036854775807"/>  
<IPermission class="System.Security.Permissions.ReflectionPermission,
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Flags="RestrictedMemberAccess"/>  
<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Flags="Execution, ControlThread, ControlPrincipal, RemotingConfiguration"/>  
<IPermission class="System.Data.SqlClient.SqlClientPermission, System.Data,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Unrestricted="true"/>  
<IPermission class="System.Net.DnsPermission, System, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Unrestricted="true"/>  
<IPermission class="System.Net.WebPermission, System, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Unrestricted="true"/>  
<IPermission class="System.Drawing.Printing.PrintingPermission,
System.Drawing, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a"  
version="1"  
Level="DefaultPrinting"/>  
<IPermission class="System.Security.Permissions.TypeDescriptorPermission,
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Unrestricted="true"/>  
<IPermission class="System.Web.AspNetHostingPermission, System,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Level="Medium"/>  
<IPermission class="System.Net.Mail.SmtpPermission, System, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
Access="Connect"/>  
</PermissionSet>  
  
PermissionState=<IPermission
class="System.Security.Permissions.FileIOPermission, mscorlib,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"  
version="1"  
PathDiscovery="C:\Windows\system32"/>  
  
RefusedSet=""  
Url=file:///C:/Windows/Microsoft.Net/assembly/GAC_32/WebDev.WebHost40/v4.0_10.
0.0.0__b03f5f7f11d50a3a/WebDev.WebHost40.dll  
StackTrace:  

    
    
       at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
       at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
       at System.Security.CodeAccessPermission.Demand()
       at System.Environment.get_SystemDirectory()
       at Microsoft.VisualStudio.WebHost.Request.MapPath(String path)
       at Microsoft.VisualStudio.WebHost.Request.ParseRequestLine()
       at Microsoft.VisualStudio.WebHost.Request.TryParseRequest()
       at Microsoft.VisualStudio.WebHost.Request.Process()
       at Microsoft.VisualStudio.WebHost.Host.ProcessRequest(Connection conn)
       at Microsoft.VisualStudio.WebHost.Host.ProcessRequest(Connection conn)
       at Microsoft.VisualStudio.WebHost.Server.OnSocketAccept(Object acceptedSocket)
       at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

InnerException:  

  1. If i publish the same code to IIS, the exception doesnt appear anymore. 
  2. If i run the solution, by setting it to run under the local IIS, again, the exception doesnt appear. 
  3. If i modify the trust level in the web.config from "medium" to "Full" again the exception doesnt appear.   

Is this normal behaviour?  
  
Thank you,  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 17819](http://orchard.codeplex.com/workitem/17819)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 11, 2011 at 3:57 PM
**Reported by:**	ccriveteanu
**Updated on:**	May 11, 2011 at 7:06 PM
**Updated by:**	BertrandLeRoy
**Closed on:**	May 11, 2011 at 7:06 PM
**Closed by:**	BertrandLeRoy
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 11, 2011 at 3:57 PM
**Reported by:**	ccriveteanu
**Updated on:**	May 11, 2011 at 7:06 PM
**Updated by:**	BertrandLeRoy
**Closed on:**	May 11, 2011 at 7:06 PM
**Closed by:**	BertrandLeRoy

**Comment by bleroy** [comment]
On *2011-05-12 00:53:00 UTC*, **@BertrandLeRoy** commented:

Does it repro without advanced menu?

**Comment by bleroy** [comment]
On *2011-05-12 01:35:44 UTC*, **@ccriveteanu** commented:

No, it actually doesnt repro with the simple menu.
I've also informed Pyotr about the issue.

**Comment by bleroy** [comment]
On *2011-05-12 02:06:10 UTC*, **@BertrandLeRoy** commented:

Thanks. So if you don't mind I'll close this and let you open a bug on the advanced menu site. If it's determined that a bug in Orchard is causing this, it's fine to open a new bug with the specifics of course.
