### ISSUE TITLE
Package installation failed.

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#1849]
I have a fresh installation of Orchard 1.2 installed on Win 2008 Server 64.
Any time I try to install a module from the gallery I receive the following
errors:  
  
Package installation failed.  
  
There was an error installing the requested package. This can happen if the
server does not have write access to the '~/Modules' or '~/Themes' folder of
the web site. If the site is running in shared hosted environement, adding
write access to these folders sometimes needs to be done manually through the
Hoster control panel. Once Themes and Modules have been installed, it is
recommended to remove write access to these folders.  
  
Input string was not in a correct format.  
  
I have done my best to verify that the account used by IIS and the Application
Pool have read write permissions on those two folders.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 17959](http://orchard.codeplex.com/workitem/17959)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jun 16, 2011 at 8:10 PM
**Reported by:**	Goudinov
**Updated on:**	Dec 1, 2011 at 1:16 AM
**Updated by:**	sebastienros
**Closed on:**	Dec 1, 2011 at 1:16 AM
**Closed by:**	sebastienros
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jun 16, 2011 at 8:10 PM
**Reported by:**	Goudinov
**Updated on:**	Dec 1, 2011 at 1:16 AM
**Updated by:**	sebastienros
**Closed on:**	Dec 1, 2011 at 1:16 AM
**Closed by:**	sebastienros

**Comment by bleroy** [comment]
On *2011-08-03 01:13:35 UTC*, **@BertrandLeRoy** commented:

Do you have a stack trace?

**Comment by bleroy** [comment]
On *2011-08-03 01:13:53 UTC*, **@BertrandLeRoy** commented:

(you can find stack traces in app_data/logs)

**Comment by bleroy** [comment]
On *2011-08-03 02:04:36 UTC*, **@Goudinov** commented:

j'suis desolé Bertrand, but I ended up removing and completely re-installing Orchard so that I could continue. If it happens again, I'll update this thread.

**Comment by bleroy** [comment]
On *2011-08-05 15:01:22 UTC*, **@agriffard** commented:

I have a similar error.
Here is the stack trace :

2011-07-25 13:37:49,090 [17] Orchard.Packaging.Controllers.PackagingServicesController - L'installation du paquetage a échoué.
Orchard.OrchardException: There was an error installing the requested package. This can happen if the server does not have write access to the '~/Modules' or '~/Themes' folder of the web site. If the site is running in shared hosted environement, adding write
 access to these folders sometimes needs to be done manually through the Hoster control panel. Once Themes and Modules have been installed, it is recommended to remove write access to these folders. ---> System.FormatException: Input string was not in a
 correct format.
at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
at System.Version.TryParseVersion(String version, VersionResult& result)
at System.Version.Parse(String input)
at Orchard.Packaging.Services.ExtensionReferenceRepository.<GetPackages>b__4(<>f__AnonymousType22 <>h__TransparentIdentifier0)
at System.Linq.Enumerable.<>c__DisplayClass123.<CombineSelectors>b__11(TSource x)
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.OrderedEnumerable1.<GetEnumerator>d__0.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.OrderedEnumerable1.<GetEnumerator>d__0.MoveNext()
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source)
at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, Version version)
at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId)
at NuGet.ProjectInstallWalker.OnBeforeDependencyWalk(IPackage package)
at NuGet.PackageWalker.Walk(IPackage package)
at NuGet.InstallWalker.ResolveOperations(IPackage package)
at NuGet.ProjectManager.Execute(IPackage package, IPackageOperationResolver resolver)
at NuGet.ProjectManager.AddPackageReference(IPackage package, Boolean ignoreDependencies)
at NuGet.ProjectManager.AddPackageReference(String packageId, Version version, Boolean ignoreDependencies)
at NuGet.ProjectManager.AddPackageReference(String packageId, Version version)
at Orchard.Packaging.Services.PackageInstaller.ExecuteInstall(IPackage package, IPackageRepository packageRepository, String sourceLocation, String targetPath)
at Orchard.Packaging.Services.PackageInstaller.InstallPackage(IPackage package, IPackageRepository packageRepository, String location, String applicationPath)
at Orchard.Packaging.Services.PackageManager.<>c__DisplayClass8.<Install>b__7()
at Orchard.Packaging.Services.PackageManager.DoInstall(Func1 installer)
--- End of inner exception stack trace ---
at Orchard.Packaging.Services.PackageManager.DoInstall(Func1 installer)
at Orchard.Packaging.Controllers.PackagingServicesController.InstallGallery(String packageId, String version, Int32 sourceId, String redirectUrl)

**Comment by bleroy** [comment]
On *2011-10-12 03:01:53 UTC*, **@BertrandLeRoy** commented:

I've seen that several times but we were never able to completely determine what was causing it. The outcome of investigating this may be a doc topic or FAQ entry.

**Comment by bleroy** [comment]
On *2011-11-12 12:32:48 UTC*, **@DrZim** commented:

My Orchard-error-2011.11.12.log is identical to the 7-25-2011 post, minus the localization.

It seems easy to reproduce: fresh install of Orchard in the zip file pre-compiled state, Windows 2008 Server Web x64, IIS 7 in x64 mode, App Pool with custom login, permissions set on the four folders for the app pool to "Modify, Read & Execute, List
 folder contents, Read, Write", but not "Special permissions, Full control". Login to SQL server set with integrated security (it created tables.) Login in SQL has the four roles assigned (ddladmin, securityadmin, datareader, datawriter.)

I loaded modules starting with the first and right around the 28th one, it fails, then continues to fail with the same error even if you uninstall modules.

**Comment by bleroy** [comment]
On *2011-11-12 12:46:42 UTC*, **@DrZim** commented:

Deleting everything in the App_Data directory and starting over with existing modules does not fix the issue.

**Comment by bleroy** [comment]
On *2011-11-19 04:12:38 UTC*, **@mikehc** commented:

Make sure u don't have a "invalid" version in one of your Theme.txt files. I had to change the version of one theme from "1" to "1.0" for it to work.
