### ISSUE TITLE
System.Web.Mvc.HttpAntiForgeryException was unhandled by user code

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#193]
After logging out of a Contributor user account & immediately trying to login
with an Admin user account, I got the following exception message:  
  
System.Web.Mvc.HttpAntiForgeryException was unhandled by user code  
Message="A required anti-forgery token was not supplied or was invalid."  
Source="System.Web.Mvc"  
ErrorCode=-2147467259  
StackTrace:  

    
    
       at System.Web.Mvc.AntiForgeryDataSerializer.Deserialize(String serializedToken)
       at System.Web.Mvc.ValidateAntiForgeryTokenAttribute.OnAuthorization(AuthorizationContext filterContext)
       at Orchard.Mvc.AntiForgery.AntiForgeryAuthorizationFilter.OnAuthorization(AuthorizationContext filterContext) in X:\D4\Orchard\src\Orchard\Mvc\AntiForgery\AntiForgeryAuthorizationFilter.cs:line 36
       at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
       at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)

InnerException: System.FormatException  

    
    
       Message="Invalid length for a Base-64 char array."
       Source="mscorlib"
       StackTrace:
            at System.Convert.FromBase64String(String s)
            at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString)
            at System.Web.UI.ObjectStateFormatter.System.Web.UI.IStateFormatter.Deserialize(String serializedState)
            at System.Web.Mvc.AntiForgeryDataSerializer.Deserialize(String serializedToken)
       InnerException: 

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 16303](http://orchard.codeplex.com/workitem/16303)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 10, 2010 at 4:12 AM
**Reported by:**	rdaddis
**Updated on:**	May 10, 2010 at 11:17 PM
**Updated by:**	bradmi
**Closed on:**	May 10, 2010 at 11:17 PM
**Closed by:**	bradmi
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 10, 2010 at 4:12 AM
**Reported by:**	rdaddis
**Updated on:**	May 10, 2010 at 11:17 PM
**Updated by:**	bradmi
**Closed on:**	May 10, 2010 at 11:17 PM
**Closed by:**	bradmi

**Comment by bleroy** [comment]
On *2010-03-10 12:50:27 UTC*, **rdaddis** commented:

changeset # 944 (5393fcf261f0) - steps to repro:

logon with contributor role click Admin link click Manage Blogs attempt to remove a blog created by an administrator when you get the Access Denied page, logout. the Access Denied page still appears, but now it has an option to logon. when I entered the Admin user credentials, I can repro the error message.

The url shown in the browser is http://localhost:30320/Users/Account/AccessDenied?ReturnUrl=/Admin/Blogs/blog-1-title/Posts/20/Delete?__RequestVerificationToken=MlW7VckfcrlzR27QvtNPfkgYlvJ5dd3T5z1pS%252fGQp0MrhLBWH2Wbzo8odaa%252fCpY7rFt9A8kBvlvvWMkABPmuEy8DhFVYeb8sAoLMttYkrsEfxscoP3R7wwP9hQ1dDdtE&__RequestVerificationToken=MlW7VckfcrlzR27QvtNPfkgYlvJ5dd3T5z1pS/GQp0MrhLBWH2Wbzo8odaa/CpY7rFt9A8kBvlvvWMkABPmuEy8DhFVYeb8sAoLMttYkrsEfxscoP3R7wwP9hQ1dDdtE

**Comment by bleroy** [comment]
On *2010-03-27 05:14:39 UTC*, **BertrandLeRoy** commented:

Needs investigation.
