### ISSUE TITLE
TransactionScope / object disposed

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#2296]
Had this three times today, on Autoroute fork merged up to latest 1.x. Seems
to be the same stack trace each time, as follows. Always when making a change
and then refreshing the page to trigger recompile. It definitely seems to be
happening less though!  
  
  
Server Error in '/OrchardLocal' Application.  
  
  
Cannot access a disposed object.  
Object name: 'TransactionScope'.  
Description: An unhandled exception occurred during the execution of the
current web request. Please review the stack trace for more information about
the error and where it originated in the code.  
  
Exception Details: System.ObjectDisposedException: Cannot access a disposed
object.  
Object name: 'TransactionScope'.  
  
Source Error:  
  
  
  
Line 41: if (!_cancelled) {  
Line 42: Logger.Debug("Marking transaction as complete");  
Line 43: _scope.Complete();  
Line 44: }  
Line 45:  
Source File: G:\Orchard\Downplay\src\Orchard\Data\TransactionManager.cs
Line: 43  
  
Stack Trace:  
  
  
  
[ObjectDisposedException: Cannot access a disposed object.  
Object name: 'TransactionScope'.]  
System.Transactions.TransactionScope.Complete() +83955  
Orchard.Data.TransactionManager.System.IDisposable.Dispose() in
G:\Orchard\Downplay\src\Orchard\Data\TransactionManager.cs:43  
Autofac.Core.Disposer.Dispose(Boolean disposing) +79  
Autofac.Util.Disposable.Dispose() +46  
Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing) +57  
Autofac.Util.Disposable.Dispose() +46  
Orchard.Environment.DefaultOrchardHost.DisposeShellContext() in
G:\Orchard\Downplay\src\Orchard\Environment\DefaultOrchardHost.cs:204  
Orchard.Environment.DefaultOrchardHost.<MonitorExtensions>b__6(AcquireContext
` 1 ctx) in
G:\Orchard\Downplay\src\Orchard\Environment\DefaultOrchardHost.cs:189  
Orchard.Caching.Cache  ` 2.CreateEntry(TKey k, Func ` 2 acquire) in
G:\Orchard\Downplay\src\Orchard\Caching\Cache.cs:57  
Orchard.Caching.Cache  ` 2.UpdateEntry(CacheEntry currentEntry, TKey k, Func `
2 acquire) in G:\Orchard\Downplay\src\Orchard\Caching\Cache.cs:33  
Orchard.Caching.<>c__DisplayClass2.<Get>b__1(TKey k, CacheEntry currentEntry)
in G:\Orchard\Downplay\src\Orchard\Caching\Cache.cs:21  
System.Collections.Concurrent.ConcurrentDictionary  ` 2.AddOrUpdate(TKey key,
Func ` 2 addValueFactory, Func ` 3 updateValueFactory) +81  
Orchard.Caching.Cache ` 2.Get(TKey key, Func ` 2 acquire) in
G:\Orchard\Downplay\src\Orchard\Caching\Cache.cs:17  
Orchard.Caching.DefaultCacheManager.Get(TKey key, Func ` 2 acquire) in
G:\Orchard\Downplay\src\Orchard\Caching\DefaultCacheManager.cs:33  
Orchard.Environment.DefaultOrchardHost.MonitorExtensions() in
G:\Orchard\Downplay\src\Orchard\Environment\DefaultOrchardHost.cs:185  
Orchard.Environment.DefaultOrchardHost.BeginRequest() in
G:\Orchard\Downplay\src\Orchard\Environment\DefaultOrchardHost.cs:213  
Orchard.Environment.DefaultOrchardHost.Orchard.Environment.IOrchardHost.BeginR
equest() in
G:\Orchard\Downplay\src\Orchard\Environment\DefaultOrchardHost.cs:78  
Orchard.Web.MvcApplication.HostBeginRequest(HttpApplication application,
IOrchardHost host) in G:\Orchard\Downplay\src\Orchard.Web\Global.asax.cs:38  
Orchard.WarmupStarter.Starter  ` 1.OnBeginRequest(HttpApplication application)
in G:\Orchard\Downplay\src\Orchard.WarmupStarter\Starter.cs:68  
Orchard.Web.MvcApplication.Application_BeginRequest() in
G:\Orchard\Downplay\src\Orchard.Web\Global.asax.cs:29  
  
[TargetInvocationException: Exception has been thrown by the target of an
invocation.]  
System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object
target, Object[] arguments, SignatureStruct& sig, MethodAttributes
methodAttributes, RuntimeType typeOwner) +0  
System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object
target, Object[] arguments, Signature sig, MethodAttributes methodAttributes,
RuntimeType typeOwner) +72  
System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean
skipVisibilityChecks) +335  
System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +28  
System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +19  
System.Web.Util.ArglessEventHandlerProxy.Callback(Object sender, EventArgs e)
+57  
System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Ex
ecute() +148  
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&
completedSynchronously) +75  
  
  
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET
Version:4.0.30319.237  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 18406](http://orchard.codeplex.com/workitem/18406)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Feb 3, 2012 at 5:03 PM
**Reported by:**	randompete
**Updated on:**	Feb 8, 2012 at 7:48 PM
**Updated by:**	BertrandLeRoy
**Closed on:**	Feb 8, 2012 at 7:48 PM
**Closed by:**	BertrandLeRoy
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Feb 3, 2012 at 5:03 PM
**Reported by:**	randompete
**Updated on:**	Feb 8, 2012 at 7:48 PM
**Updated by:**	BertrandLeRoy
**Closed on:**	Feb 8, 2012 at 7:48 PM
**Closed by:**	BertrandLeRoy

**Comment by bleroy** [comment]
On *2012-02-05 06:42:35 UTC*, **@randompete** commented:

Just got another variant of the error, haven't seen this before. This was when just loading pages, nothing had been changed or enabled, but suddenly started getting it on loads of requests: Server Error in '/' Application. The transaction has aborted.
 Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. Exception Details: System.Transactions.TransactionAbortedException:
 The transaction has aborted. Source Error: Line 24: if (_scope == null) { Line 25: Logger.Debug("Creating transaction on Demand"); Line 26: _scope = new TransactionScope( Line 27: TransactionScopeOption.Required, Line 28: new TransactionOptions { Source File:
 G:\Orchard\Default\src\Orchard\Data\TransactionManager.cs Line: 26 Stack Trace: [TransactionAbortedException: The transaction has aborted.] System.Transactions.TransactionStatePromotedAborted.CreateAbortingClone(InternalTransaction tx) +44 System.Transactions.DependentTransaction..ctor(IsolationLevel
 isoLevel, InternalTransaction internalTransaction, Boolean blocking) +112 System.Transactions.Transaction.DependentClone(DependentCloneOption cloneOption) +143 System.Transactions.TransactionScope.SetCurrent(Transaction newCurrent) +110 System.Transactions.TransactionScope.PushScope()
 +38 System.Transactions.TransactionScope..ctor(TransactionScopeOption scopeOption, TransactionOptions transactionOptions) +743 Orchard.Data.TransactionManager.Orchard.Data.ITransactionManager.Demand() in G:\Orchard\Default\src\Orchard\Data\TransactionManager.cs:26
 Orchard.Data.SessionLocator.For(Type entityType) in G:\Orchard\Default\src\Orchard\Data\SessionLocator.cs:31 Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter..ctor(ShellSettings shellSettings, ISessionLocator sessionLocator, IEnumerable`1
 commandInterpreters, ISessionFactoryHolder sessionFactoryHolder, IReportsCoordinator reportsCoordinator) in G:\Orchard\Default\src\Orchard\Data\Migration\Interpreters\DefaultDataMigrationInterpreter.cs:36 [DependencyResolutionException: An exception was thrown
 while invoking the constructor 'Void .ctor(Orchard.Environment.Configuration.ShellSettings, Orchard.Data.ISessionLocator, System.Collections.Generic.IEnumerable`1[Orchard.Data.Migration.Interpreters.ICommandInterpreter], Orchard.Data.ISessionFactoryHolder,
 Orchard.Reports.Services.IReportsCoordinator)' on type 'DefaultDataMigrationInterpreter'.] Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +261 Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext
 context, IEnumerable`1 parameters) +182 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +48 Autofac.Core.Resolving.InstanceLookup.<Execute>b__6() +11 Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
 +106 Autofac.Core.Resolving.InstanceLookup.Execute() +132 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration
 registration, IEnumerable`1 parameters) +23 Autofac.Core.Activators.Reflection.<>c__DisplayClass2.<CanSupplyValue>b__0() +31 Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +111 Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext
 context, IEnumerable`1 parameters) +182 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +48 Autofac.Core.Resolving.InstanceLookup.<Execute>b__6() +11 Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
 +106 Autofac.Core.Resolving.InstanceLookup.Execute() +132 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration
 registration, IEnumerable`1 parameters) +23 Autofac.Core.Activators.Reflection.<>c__DisplayClass2.<CanSupplyValue>b__0() +31 Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +111 Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext
 context, IEnumerable`1 parameters) +182 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +48 Autofac.Core.Resolving.InstanceLookup.<Execute>b__6() +11 Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
 +106 Autofac.Core.Resolving.InstanceLookup.Execute() +132 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration
 registration, IEnumerable`1 parameters) +23 Autofac.Features.Collections.<>c__DisplayClass6.<RegistrationsFor>b__1(IComponentRegistration cr) +17 System.Linq.WhereSelectArrayIterator`2.MoveNext() +85 System.Linq.Buffer`1..ctor(IEnumerable`1 source) +325 System.Linq.Enumerable.ToArray(IEnumerable`1
 source) +78 Autofac.Features.Collections.<>c__DisplayClass4.<RegistrationsFor>b__0(IComponentContext c, IEnumerable`1 p) +135 Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +30 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1
 parameters) +48 Autofac.Core.Resolving.InstanceLookup.Execute() +48 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration
 registration, IEnumerable`1 parameters) +23 Autofac.Core.Registration.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) +19 Autofac.Builder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) +17 Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext
 context, IEnumerable`1 parameters) +30 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +48 Autofac.Core.Resolving.InstanceLookup.Execute() +48 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope,
 IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +23 Autofac.Core.Activators.Reflection.<>c__DisplayClass2.<CanSupplyValue>b__0()
 +31 Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +111 Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +182 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1
 parameters) +48 Autofac.Core.Resolving.InstanceLookup.<Execute>b__6() +11 Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator) +106 Autofac.Core.Resolving.InstanceLookup.Execute() +132 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope
 currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +23 Autofac.Core.Activators.Reflection.<>c__DisplayClass2.<CanSupplyValue>b__0()
 +31 Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +111 Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +182 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1
 parameters) +48 Autofac.Core.Resolving.InstanceLookup.<Execute>b__6() +11 Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator) +106 Autofac.Core.Resolving.InstanceLookup.Execute() +132 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope
 currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +23 Autofac.Features.Collections.<>c__DisplayClass6.<RegistrationsFor>b__1(IComponentRegistration
 cr) +17 System.Linq.WhereSelectArrayIterator`2.MoveNext() +85 System.Linq.Buffer`1..ctor(IEnumerable`1 source) +325 System.Linq.Enumerable.ToArray(IEnumerable`1 source) +78 Autofac.Features.Collections.<>c__DisplayClass4.<RegistrationsFor>b__0(IComponentContext
 c, IEnumerable`1 p) +135 Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +30 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +48 Autofac.Core.Resolving.InstanceLookup.Execute()
 +48 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration,
 IEnumerable`1 parameters) +23 Autofac.Core.Registration.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) +19 Autofac.Builder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) +17 Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext
 context, IEnumerable`1 parameters) +30 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +48 Autofac.Core.Resolving.InstanceLookup.Execute() +48 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope,
 IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +23 Autofac.Core.Activators.Reflection.<>c__DisplayClass2.<CanSupplyValue>b__0()
 +31 Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +111 Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +182 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1
 parameters) +48 Autofac.Core.Resolving.InstanceLookup.Execute() +48 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration
 registration, IEnumerable`1 parameters) +23 Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) +72 Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service
 service, IEnumerable`1 parameters) +54 Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service) +10 Orchard.Environment.ShellBuilders.<>c__DisplayClassb.<CreateContainer>b__a(IActivatingEventArgs`1 e) in G:\Orchard\Default\src\Orchard\Environment\ShellBuilders\ShellContainerFactory.cs:105
 Autofac.Builder.<>c__DisplayClass6.<OnActivating>b__5(Object s, ActivatingEventArgs`1 e) +129 System.EventHandler`1.Invoke(Object sender, TEventArgs e) +0 Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1
 parameters, Object& instance) +54 Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +128 Autofac.Core.Resolving.InstanceLookup.Execute() +48 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope,
 IComponentRegistration registration, IEnumerable`1 parameters) +164 Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) +70 Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration
 registration, IEnumerable`1 parameters) +155 Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) +72 Autofac.ResolutionExtensions.TryResolveService(IComponentContext context,
 Service service, Object& instance) +21 Orchard.Mvc.OrchardControllerFactory.TryResolve(WorkContext workContext, Object serviceKey, T& instance) in G:\Orchard\Default\src\Orchard\Mvc\OrchardControllerFactory.cs:26 Orchard.Mvc.OrchardControllerFactory.GetControllerInstance(RequestContext
 requestContext, Type controllerType) in G:\Orchard\Default\src\Orchard\Mvc\OrchardControllerFactory.cs:71 System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) +74 System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase
 httpContext, IController& controller, IControllerFactory& factory) +232 System.Web.Mvc.<>c__DisplayClass6.<BeginProcessRequest>b__2() +49 System.Web.Mvc.<>c__DisplayClassb`1.<ProcessInApplicationTrust>b__a() +13 System.Web.Mvc.SecurityUtil.<GetCallInAppTrustThunk>b__0(Action
 f) +7 System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Action action) +22 System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Func`1 func) +124 System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object
 state) +98 System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +50 System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
 +16 Orchard.Mvc.Routes.HttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) in G:\Orchard\Default\src\Orchard\Mvc\Routes\ShellRoute.cs:141 System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
 +8963444 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +184 Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.237

**Comment by bleroy** [comment]
On *2012-02-06 00:11:24 UTC*, **@sebastienros** commented:

Could you try with the latest changeset in 1.x ?

**Comment by bleroy** [comment]
On *2012-02-06 21:29:09 UTC*, **@Piedone** commented:

This might be helpful, although it's from an earlier changeset (I don't know which one because I didn't use the source as a repo but I updated on the 3rd of January to the latest 1.x changeset that time). This happens if I refresh on the setup page:

System.ObjectDisposedException was unhandled by user code
Message=Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
Source=Autofac
ObjectName=""
StackTrace:
   at Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed()
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.ShapeAttributeBindingStrategy.<>c__DisplayClass4.<CreateDelegate>b__3(DisplayContext context) in D:\Lehoczky Zoltan\Documents\Weblapok\Orchard Teszt\src\Orchard\DisplayManagement\Descriptors\ShapeAttributeStrategy\ShapeAttributeBindingStrategy.cs:line 52
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass3.<>c__DisplayClass5.<BoundAs>b__2(DisplayContext displayContext) in D:\Lehoczky Zoltan\Documents\Weblapok\Orchard Teszt\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 55
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in D:\Lehoczky Zoltan\Documents\Weblapok\Orchard Teszt\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 179
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) in D:\Lehoczky Zoltan\Documents\Weblapok\Orchard Teszt\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 88
   at Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape) in D:\Lehoczky Zoltan\Documents\Weblapok\Orchard Teszt\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 71
   at Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable`1 parameters) in D:\Lehoczky Zoltan\Documents\Weblapok\Orchard Teszt\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 38
   at Orchard.DisplayManagement.Implementation.DisplayHelperFactory.DisplayHelperBehavior.InvokeMember(Func`1 proceed, Object target, String name, INamedEnumerable`1 args) in D:\Lehoczky Zoltan\Documents\Weblapok\Orchard Teszt\src\Orchard\DisplayManagement\Implementation\DisplayHelperFactory.cs:line 27
   at ClaySharp.ClayBehaviorCollection.<>c__DisplayClass14.<>c__DisplayClass16.<InvokeMember>b__13() in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 29
   at ClaySharp.ClayBehaviorCollection.Execute(Func`1 proceed, Func`3 linker) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 13
   at ClaySharp.ClayBehaviorCollection.InvokeMember(Func`1 proceed, Object self, String name, INamedEnumerable`1 args) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 29
   at ASP._Page_Themes_SafeMode_Views_Layout_cshtml.Execute() in d:\Orchard\src\Orchard.Web\Themes\SafeMode\Views\Layout.cshtml:line 31
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit) in D:\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeTemplateStrategy\ShapeTemplateBindingStrategy.cs:line 133
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.<>c__DisplayClass26.<>c__DisplayClass28.<Discover>b__15(DisplayContext displayContext) in D:\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeTemplateStrategy\ShapeTemplateBindingStrategy.cs:line 117
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass3.<>c__DisplayClass5.<BoundAs>b__2(DisplayContext displayContext) in D:\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 55
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in D:\Orchard\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 179
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) in D:\Orchard\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 88
   at Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape) in D:\Orchard\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 71
   at Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable`1 parameters) in D:\Orchard\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 38
   at Orchard.DisplayManagement.Implementation.DisplayHelperFactory.DisplayHelperBehavior.InvokeMember(Func`1 proceed, Object target, String name, INamedEnumerable`1 args) in D:\Orchard\src\Orchard\DisplayManagement\Implementation\DisplayHelperFactory.cs:line 27
   at ClaySharp.ClayBehaviorCollection.<>c__DisplayClass14.<>c__DisplayClass16.<InvokeMember>b__13() in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 29
   at ClaySharp.ClayBehaviorCollection.Execute(Func`1 proceed, Func`3 linker) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 13
   at ClaySharp.ClayBehaviorCollection.InvokeMember(Func`1 proceed, Object self, String name, INamedEnumerable`1 args) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 29
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.<>c__DisplayClass7.<FindView>b__5(ViewContext viewContext, TextWriter writer, IViewDataContainer viewDataContainer) in D:\Orchard\src\Orchard\Mvc\ViewEngines\ThemeAwareness\LayoutAwareViewEngine.cs:line 63
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.LayoutView.Render(ViewContext viewContext, TextWriter writer) in D:\Orchard\src\Orchard\Mvc\ViewEngines\ThemeAwareness\LayoutAwareViewEngine.cs:line 90
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
InnerException:
