### ISSUE TITLE
Reference to Clay source

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#2323]
I am probably abusing MediaGarden illegally but it seems this shouldn't be in
the checked source.  
  
While running Media Garden under debugger VS asked for:  
  
C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehavior.cs  
  
then crashed in ContentItemBehavior.cs on the line:  
  
return base.GetMemberMissing(proceed, self, name);  
  
with:  
  
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException was unhandled by user
code  
Message='MediaGarden.Models.MediaPart' does not contain a definition for
'MediaSource'  
Source=Anonymously Hosted DynamicMethods Assembly  
StackTrace:  

    
    
       at lambda_method(Closure )
       at ClaySharp.ClayBehavior.GetMemberMissing(Func`1 proceed, Object self, String name) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehavior.cs:line 17
       at Orchard.ContentManagement.ContentItemBehavior.GetMemberMissing(Func`1 proceed, Object self, String name) in C:\Users\Dave\Projects\Orchard\Orchard\src\Orchard\ContentManagement\ContentItemBehavior.cs:line 18
       at Orchard.ContentManagement.ContentPartBehavior.GetMemberMissing(Func`1 proceed, Object self, String name) in C:\Users\Dave\Projects\Orchard\Orchard\src\Orchard\ContentManagement\ContentPartBehavior.cs:line 17
       at ClaySharp.ClayBehaviorCollection.<>c__DisplayClass38.<>c__DisplayClass3a.<GetMemberMissing>b__37() in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 53
       at ClaySharp.ClayBehaviorCollection.Execute(Func`1 proceed, Func`3 linker) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 13
       at ClaySharp.ClayBehaviorCollection.GetMemberMissing(Func`1 proceed, Object self, String name) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 53
       at lambda_method(Closure )
       at ClaySharp.ClayBehavior.GetMember(Func`1 proceed, Object self, String name) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehavior.cs:line 8
       at ClaySharp.ClayBehaviorCollection.<>c__DisplayClass2.<>c__DisplayClass4.<GetMember>b__1() in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 17
       at ClaySharp.ClayBehaviorCollection.Execute(Func`1 proceed, Func`3 linker) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 13
       at ClaySharp.ClayBehaviorCollection.GetMember(Func`1 proceed, Object self, String name) in C:\Users\sebros\My Projects\Clay\src\ClaySharp\ClayBehaviorCollection.cs:line 17
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at MediaGarden.ImageResizer.Filters.ImageResizingDisplayFilter.Displaying(Object context) in c:\Users\Dave\Projects\Orchard\Orchard\src\Orchard.Web\Modules\MediaGarden.ImageResizer\Filters\ImageResizingDisplayFilter.cs:line 32

InnerException:  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 18433](http://orchard.codeplex.com/workitem/18433)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Feb 15, 2012 at 3:23 AM
**Reported by:**	bsdr
**Updated on:**	Aug 15, 2012 at 4:32 PM
**Updated by:**	WebAlchemy
**Closed on:**	Feb 15, 2012 at 6:52 PM
**Closed by:**	BertrandLeRoy
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Feb 15, 2012 at 3:23 AM
**Reported by:**	bsdr
**Updated on:**	Aug 15, 2012 at 4:32 PM
**Updated by:**	WebAlchemy
**Closed on:**	Feb 15, 2012 at 6:52 PM
**Closed by:**	BertrandLeRoy

**Comment by bleroy** [comment]
On *2012-02-15 15:10:34 UTC*, **@BertrandLeRoy** commented:

I don't get it. What's the bug here and how do we reproduce it?

**Comment by bleroy** [comment]
On *2012-02-15 16:30:04 UTC*, **@bsdr** commented:

Sorry. Didn't realize ClaySharp is an included dependency. Please ignore.

**Comment by bleroy** [comment]
On *2012-02-15 20:03:00 UTC*, **@randompete** commented:

Please note Media Garden bugs should go to the project site: 
http://orchardmediagarden.codeplex.com

But, if there is a bug here, it'll be fixed in the latest Media Garden version which will be 1.4-targetted.

**Comment by bleroy** [comment]
On *2012-08-15 23:32:35 UTC*, **@WebAlchemy** commented:

Downloaded the zip of 1.5.1. Built and ran the virgin project in Debug mode. I received the same error. I removed the reference to ClaySharp in the Orchard.Framework project and re-added the Reference back, referring to the dll in the lib/claysharp directory.
 That fixed it.
