### ISSUE TITLE
Error While Creating New Blog

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#37]
Build 45266  
  
Clean download - no changes to code  
Loaded into VS2008  
Hit F5  
Register "Administrator" account  
Create new blog "nickblog"  
Add blog name to the Permalink  
Hit create  
Get error below  
hit continue  
go to Manage blogs  
See that blog is created  
click on link  
get same error.  
  
System.InvalidOperationException was unhandled by user code  
Message="The controller name 'admin' is ambiguous between the following types:
\r\nOrchard.Core.Themes.Controllers.AdminController\r\nOrchard.Core.Settings.C
ontrollers.AdminController\r\nOrchard.Tags.Controllers.AdminController\r\nOrch
ard.Users.Controllers.AdminController\r\nOrchard.Media.Controllers.AdminContro
ller\r\nOrchard.Comments.Controllers.AdminController\r\nOrchard.Pages.Controll
ers.AdminController\r\nOrchard.Roles.Controllers.AdminController"  
Source="System.Web.Mvc"  
StackTrace:  

    
    
       at System.Web.Mvc.DefaultControllerFactory.GetControllerTypeWithinNamespaces(String controllerName, HashSet`1 namespaces)
       at System.Web.Mvc.DefaultControllerFactory.GetControllerType(RequestContext requestContext, String controllerName)
       at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
       at Orchard.Mvc.OrchardControllerFactory.CreateController(RequestContext requestContext, String controllerName) in C:\Users\nickk\Documents\_SVN\Orchard\trunk\src\Orchard\Mvc\OrchardControllerFactory.cs:line 27
       at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

InnerException:  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 15872](http://orchard.codeplex.com/workitem/15872)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jan 12, 2010 at 4:16 PM
**Reported by:**	nickknyc
**Updated on:**	Feb 24, 2010 at 8:24 PM
**Updated by:**	BertrandLeRoy
**Closed on:**	Feb 24, 2010 at 8:24 PM
**Closed by:**	BertrandLeRoy

**Comment by bleroy** [comment]
On *2010-01-15 08:24:07 UTC*, **BertrandLeRoy** commented:

Can you please try again with a more recent version?

**Comment by bleroy** [comment]
On *2010-01-16 03:25:24 UTC*, **nickknyc** commented:

Error seems fixed in 45480 - but there is a little UI issue showing up ([todo: (heskew) need path to here]/ ). But I think you can close this issue - thanks.
