### ISSUE TITLE
The controller for path '/Themes/TheAdminClassic/Theme.png' was not found or does not implement IController.

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#53]
Changset #589 (0f0ec5cd4bec) - when I request [ http://localhost/Admin/Themes,
I get: System.Web.HttpException ](http://localhost/Admin/Themes, I get:

System.Web.HttpException) was unhandled by user code  
Message="The controller for path '/Themes/TheAdminClassic/Theme.png' was not
found or does not implement IController."  
Source="System.Web.Mvc"  
ErrorCode=-2147467259  
StackTrace:  

    
    
       at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
       at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
       at Orchard.Mvc.OrchardControllerFactory.CreateController(RequestContext requestContext, String controllerName) in R:\Lib\Orchard\src\Orchard\Mvc\OrchardControllerFactory.cs:line 27
       at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

InnerException:  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 16221](http://orchard.codeplex.com/workitem/16221)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Feb 4, 2010 at 2:17 AM
**Reported by:**	rdaddis
**Updated on:**	May 10, 2010 at 11:49 PM
**Updated by:**	bradmi
**Closed on:**	May 10, 2010 at 11:49 PM
**Closed by:**	bradmi

**Comment by bleroy** [comment]
On *2010-02-25 04:02:59 UTC*, **BertrandLeRoy** commented:

Repro: remove the theme.png from one of the themes, go to the manage themes screen. Exception.
This only repros in debug mode.
