### ISSUE TITLE
Themes - Theme.gif and Themes/Themes Missing!

### ISSUE THREAD

**Issue by bleroy** [bleroy/OrchardImportTest#72]
1 Start up site  

  1. Admin 
  2. Manage Themes   

Blows Twice. Both errors are below. The fix is to make sure you have a
Themes.Gif file and the /Themes/Themes directory with the relevant gif in.  
  
System.Web.HttpException was unhandled by user code  
Message="The controller for path '/Themes/Themes/Theme.gif' was not found or
does not implement IController."  
Source="System.Web.Mvc"  
ErrorCode=-2147467259  
StackTrace:  

    
    
       at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
       at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
       at Orchard.Mvc.OrchardControllerFactory.CreateController(RequestContext requestContext, String controllerName) in D:\InformationServices\Prototypes\CMS\orchard-44272\trunk\src\Orchard\Mvc\OrchardControllerFactory.cs:line 27
       at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

InnerException:  
  
  
  
  
  
System.Web.HttpException was unhandled by user code  
Message="The controller for path '/Themes/TheAdmin/Theme.gif' was not found or
does not implement IController."  
Source="System.Web.Mvc"  
ErrorCode=-2147467259  
StackTrace:  

    
    
       at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
       at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
       at Orchard.Mvc.OrchardControllerFactory.CreateController(RequestContext requestContext, String controllerName) in D:\InformationServices\Prototypes\CMS\orchard-44272\trunk\src\Orchard\Mvc\OrchardControllerFactory.cs:line 27
       at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
       at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

InnerException:  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 15512](http://orchard.codeplex.com/workitem/15512)
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 18, 2009 at 1:30 PM
**Reported by:**	Jetski5822
**Updated on:**	Dec 18, 2009 at 4:24 PM
**Updated by:**	skewed
**Closed on:**	Dec 18, 2009 at 4:24 PM
**Status:**	Closed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 18, 2009 at 1:30 PM
**Reported by:**	Jetski5822
**Updated on:**	Dec 18, 2009 at 4:24 PM
**Updated by:**	skewed
**Closed on:**	Dec 18, 2009 at 4:24 PM

**Comment by bleroy** [comment]
On *2009-12-19 00:24:06 UTC*, **skewed** commented:

The themes were (and are still) being worked on hence the disorder in the theme selector. Those themes won't work BTW, they're all identifiable as themes (folder in ~/Themes containing a Theme.txt) but contain anything to override the rendered page. Expect
 some working themes to be hooked up in the near future.
